name: industrial_logistics_platform
version: '1.0.0'
profile: ilp_dev

config-version: 2

vars:
  environment: dev
  data_quality_enabled: true

models:
  industrial_logistics_platform:
    +docs:
      node_color: "#3498db"
    staging:
      +schema: staging
      +materialized: view
    trusted:
      +schema: trusted
      +materialized: table
    refined:
      +schema: refined
      +materialized: table

on-run-start:
  - "SET search_path TO {{ target.schema }}"

quoting:
  identifier: true
  schema: false
  database: false

tests:
  +store_failures: true
  +store_failures_as: table

