ilp_dev:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_LAKEHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_LAKEHOUSE_PORT', '5432') }}"
      user: "{{ env_var('POSTGRES_USER', 'lakehouse') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_LAKEHOUSE_DB', 'lakehouse') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_LAKEHOUSE_HOST') }}"
      port: "{{ env_var('POSTGRES_LAKEHOUSE_PORT', '5432') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_LAKEHOUSE_DB', 'lakehouse') }}"
      schema: staging
      threads: 16
      keepalives_idle: 0
      connect_timeout: 10
